Repository Lucifer6102/Hacktoberfest2k21, pull requests merged in 2021-10, with the labels that each got.

#1 Added CPP file
  sam1.cpp
Labels: hacktoberfest2021, accepted

#2 Added Java file
  sam2.java
Labels: hacktoberfest2021, accepted, hactoberfest

#3 Update README.md
  README.md
Labels: hacktoberfest2021, accepted

#4 Updated Readme
  README.md
Labels: hacktoberfest2021, accepted, hactoberfest

#8 Add files via upload
  kth largest element in array.cpp
  kth smallest element in array.cpp
Labels: hacktoberfest2021, accepted, hacktoberfest-accepted

#7 Update README.md
  README.md
Labels: hacktoberfest2021, accepted, hacktoberfest-accepted

#6 Create 206. Reverse Linked List
  206. Reverse Linked List
Labels: hacktoberfest2021, accepted, hacktoberfest-accepted

#5 Added Matrix-Addition C Program
  matrix-addition.c
Labels: hacktoberfest2021, accepted, hacktoberfest-accepted

#13 Lowest Common Factor
  Lowest_common_factor.cpp
Labels: hacktoberfest2021, accepted, hacktoberfest-accepted

#15 Added Linked list
  add_1_at_end.cpp
  add_2_linked_list.cpp
Labels: hacktoberfest2021, accepted, hacktoberfest-accepted

#20 Update sam2.java
  sam2.java
Labels: hacktoberfest2021, accepted, hacktoberfest-accepted
